### PR TITLE
[#132]: Proposed Fix - "Plot `show` Method Not Working on Windows 10"

### PR DESCRIPTION
**Pull request by M-NK-Y**
Changes `show_with_default_app` for `target_os = "windows"` to make use of `spawn` in place of `output` when attempting to open the temporary HTML file using the user's default browser. Additionally provides arguments within a shared object delegating command formatting to `std::process:Command`, which going forwards I think will be a safe bet to ensure path correctness.

### CODE REVIEW

**Comment by M-NK-Y** [comment]
As an aside, hopefully this isn't too late to mention in light of #129 but hopefully this proves to be a more robust solution going forwards by having the path formatting performed within the same `args` method.

**Comment by mfreeborn** [comment]
Thanks for looking in to this.

Are you also able to change the latest changelog entry from:

`Thanks to [@juanespj](https://github.com/juanespj) for the PR.`

to

`Thanks to [@juanespj](https://github.com/juanespj) and [@M-NK-Y](https://github.com/M-NK-Y) for the PRs.`

**Comment by M-NK-Y** [comment]
Done!

**Comment by khoitsma** [comment]
Question:

- Is the "Plot show not working in Windows 10" problem fixed in 0.8.3 ?
- Or is it to be fixed in 0.8.4 ?

In Windows 11, using 0.8.3, Plot show is not working for me

Thanks.

**Comment by fsktom** [comment]
Can confirm this works. The HTML page is opened properly on my Windows 11 machine with `plot.show()` 👍🏿

**Pull request merged**
