### PR TITLE
Remove static restriction for str ref

### PR DESCRIPTION
**Pull request by aleb**

### CODE REVIEW

**Comment by aleb** [comment]
This works fine:
```
            {{ map_plot.to_inline_html(Some("test"), 600)|safe }}
```

But this not:
```
            {{ map_plot.to_inline_html(Some("test".to_string()), 600)|safe }}
```

**Comment by kaihowl** [comment]
(You might need to target this to the `dev` branch in order to attract attention. See the following.) https://github.com/igiagkiozis/plotly/blob/c0ca69192c422862941617a72094e4e44fc9b67f/CONTRIBUTING.md?plain=1#L34-L35

**Comment by andrei-ng** [comment]
Came accross the same issue. Merging this would be useful.

**Comment by mfreeborn** [comment]
I'll review this today hopefully, and add a test case so that we can make sure there isn't a regression in the future.

**Comment by andrei-ng** [comment]
@mfreeborn, @aleb , the patch is incorrect because it is missing lifetimes. I have a fix for the above. The function signature should be 
```
pub fn to_inline_html<'a, T: Into<Option<&'a str>>>(&self, plot_div_id: T) -> String {
```
Should I fork and make a different PR or is it better we fix this already existing PR ?

**Comment by mfreeborn** [comment]
Just update the existing PR :)
________________________________

**Comment by mfreeborn** [comment]
> @mfreeborn, @aleb , the patch is incorrect because it is missing lifetimes. I have a fix for the above. The function signature should be
> 
> ```
> pub fn to_inline_html<'a, T: Into<Option<&'a str>>>(&self, plot_div_id: T) -> String {
> ```
> 
> I build locally and the examples work fine with the above.
> 
> Should I fork and make a different PR or is it better we fix it in this already existing PR ?

Hang on a sec, I've just read this properly and I believe what we are looking for is:

```rust
pub fn to_inline_html<T: Option<AsRef<str>>(&self, plot_div_id: T) -> String {
    let plot_div_id = plot_div_id.into();
    let plot_div_id = match plot_div_id {
        Some(id) => id.as_ref().to_string(),
        None => Alphanumeric.sample_string(&mut thread_rng(), 20),
    };
    self.render_inline(&plot_div_id)
}
```

**Comment by aleb** [comment]
Please create a separate PR, one that is made for the dev branch...

I'm not sure how the lifetime addition is better, if you ask me..

many thanks & let me close this

**Pull request closed without merging**
