### PR TITLE
fix Plot.show()

### LINKED ISSUE #128: plotly.show() does not work on Windows 10
By design, the API "[`plot.show()`](https://github.com/igiagkiozis/plotly/blob/49bd3a87fbaa3e507e9a2664f57feda89c35b95b/plotly/src/plot.rs#L276)" would open a default web browser to display an interactive plot.
However, under my environment(Windows 10, plotly="0.8.3"), it doesn't work. The default web browser was not opened either. 

I found out that there was an issue message from cmd:
`The process cannot access the file because it is being used by another process`

https://github.com/igiagkiozis/plotly/blob/49bd3a87fbaa3e507e9a2664f57feda89c35b95b/plotly/src/plot.rs#L465
```
//Line 465
    #[cfg(target_os = "windows")]
    fn show_with_default_app(temp_path: &str) {
        use std::process::Command;
        Command::new("cmd")
            .arg("/C")
            .arg(format!(r#"start {}"#, temp_path))
            .output()
            .expect(DEFAULT_HTML_APP_NOT_FOUND);
    }
```

After investigation, I suspect it's because, that the temp html file that should be opened was being used by another process, while this "another" process is the process itself which has not yet close the file handle in Rust program.

Could you fix this please? Thanks! :)

### PR DESCRIPTION
**Pull request by mfreeborn**
Closes #128

### CODE REVIEW

**Comment by mfreeborn** [comment]
@juanespj @GSTRonnie Any chance you could confirm this works on Windows?

**Comment by GSTRonnie** [comment]
> @juanespj @GSTRonnie Any chance you could confirm this works on Windows?

I just tested the commit and it now works for me.

**Comment by juanespj** [comment]
just tested too, working!!

**Comment by GSTRonnie** [comment]
Sorry, I tested the wrong branch. The branch mfreeborn-patch-1 doesn't work for me. It is because the scope was created in Plot::show_image(). Can you do the same in Plot::show() ?

**Comment by mfreeborn** [comment]
D'oh. How about that?

**Pull request merged**
