### PR TITLE
plot.show() fix

### PR DESCRIPTION
**Pull request by juanespj**
Moved a few things around I got this to work on my Windows 10 machine seems like Spawn() does the trick!!

### CODE REVIEW

**Comment by mfreeborn** [comment]
Thanks - but did you mean to make the code changes to the `windows` implementation? Looks like you edited the linux implementation by mistake!

**Comment by juanespj** [comment]
Hey, yes it was supposed to be windows sorry, I had tested it on a offline copy
Do you want me to correct it?

**Comment by mfreeborn** [comment]
Yes please :)

**Comment by mfreeborn** [comment]
Passing all the checks; that's good. One question though, what is the difference between the command `start` in the original code vs the `/Cstart` in this PR? I can only seem to find documentation about `start`, nothing really about the additional `/C`.

**Comment by juanespj** [comment]
> Passing all the checks; that's good. One question though, what is the difference between the command `start` in the original code vs the `/Cstart` in this PR? I can only seem to find documentation about `start`, nothing really about the additional `/C`.

the separate tags didn't make a difference on the original you had .split the message in args(), you also had the /C there, I am not sure why it is needed :(
I think the ones that made the difference are spawn() vs output().

**Comment by mfreeborn** [comment]
I found what `/C` is: https://stackoverflow.com/questions/515309/what-does-cmd-c-mean

I've just updated the file very slightly. Are you able to confirm that the latest commit (1818494) works on your computer? Then I can merge this.

**Comment by juanespj** [comment]
Hey, that is a good find super clear now!! thank you for sharing...
just ran a couple of tests on my side all good to go! :)

**Comment by mfreeborn** [comment]
Great, thanks for that :) I'll release v0.8.4 with this fix once at least #126 is merged.

**Pull request merged**
